---
title: "git_00"
author: "Jasmin Quintanilla"
date: "Summer 2024"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with a sequence of commits to the master branch.
Our project will be done using several commits to the master branch.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

’Twas brillig, and the slithy toves  
      Did gyre and gimble in the wabe:  
All mimsy were the borogoves,  
      And the mome raths outgrabe.  

“Beware the Jabberwock, my son!  
      The jaws that bite, the claws that catch!  
Beware the Jubjub bird, and shun  
      The frumious Bandersnatch!”  
      
      
## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->

Two roads diverged in a yellow wood,  
And sorry I could not travel both  
And be one traveler, long I stood  
And looked down one as far as I could  
To where it bent in the undergrowth;  

Then took the other, as just as fair,  
And having perhaps the better claim,  
Because it was grassy and wanted wear;  
Though as for that the passing there  
Had worn them really about the same,  


## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->

"The sun was shining on the sea,  
      Shining with all his might:  
He did his very best to make  
      The billows smooth and bright —  
And this was odd, because it was  
      The middle of the night.  

The moon was shining sulkily,  
      Because she thought the sun  
Had got no business to be there  
      After the day was done —  
"It's very rude of him," she said,  
      "To come and spoil the fun."  
      
      
## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->

There’s just no accounting for happiness,  
or the way it turns up like a prodigal  
who comes back to the dust at your feet  
having squandered a fortune far away.  

And how can you not forgive?  
You make a feast in honor of what  
was lost, and take from its place the finest  
garment, which you saved for an occasion  
you could not imagine, and you weep night and day  
to know that you were not abandoned,  
that happiness saved its most extreme form  
for you alone.  


